services:
  database:
    image: "postgres:latest"
    environment:
      - "POSTGRES_USER=nexusgate"
      - "POSTGRES_PASSWORD=change_me_in_production"
    volumes:
      - "./db:/var/lib/postgresql/data"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexusgate -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:latest"
    restart: on-failure

  backend:
    image: "ghcr.io/em-geeklab/nexus-gate-server:latest"
    environment:
      - "DATABASE_URL=postgres://nexusgate:change_me_in_production@database:5432/nexusgate"
      - "ADMIN_SUPER_SECRET=admin_key_change_in_production"
      - "REDIS_URL=redis://redis:6379"
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: "ghcr.io/em-geeklab/nexus-gate-web:latest"
    environment:
      - "BACKEND_URL=http://backend:3000"
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "8080:80"
